import { MameGroup } from ".";

export const namco: MameGroup = {
  name: "Namco",
  drivers: [
    "20pacgal",
    "30test",
    "airbustr",
    "baraduke",
    "cave",
    "dkmb",
    "gal3",
    "galaga",
    "galgames",
    "gaplus",
    "kungfur",
    "mappy",
    "namcofl",
    "namcona1",
    "namconb1",
    "namcond1",
    "namcops2",
    "namcos1",
    "namcos10",
    "namcos11",
    "namcos12",
    "namcos2",
    "namcos21",
    "namcos21_c67",
    "namcos21_de",
    "namcos22",
    "namcos23",
    "namcos86",
    "pacland",
    "polepos",
    "seta2",
    "shootaway2",
    "skykid",
    "tceptor",
    "toypop",
    "triforce",
    "tx1",
    "uapce",
  ]
};
