import { MameGroup } from ".";

export const sega: MameGroup = {
  name: "Sega",
  drivers: [
    "angelkds",
    "appoooh",
    "bankp",
    "calorie",
    "cclimber",
    "chihiro",
    "coolridr",
    "flashbeats",
    "freekick",
    "hikaru",
    "kyugo",
    "lindbergh",
    "marineb",
    "megaplay",
    "megatech",
    "model1",
    "model2",
    "model3",
    "monacogp",
    "naomi",
    "pengo",
    "sderby2",
    "segaatom",
    "segac2",
    "segae",
    "segahang",
    "segaorun",
    "segas16a",
    "segas16b",
    "segas18",
    "segas24",
    "segas32",
    "segasp",
    "segaxbd",
    "segaybd",
    "sg1000a",
    "stv",
    "suprloco",
    "system1",
    "system16",
    "turbo",
    "zaxxon",
  ]
};
