export const serials = {
  balsente: "Bally Sente SAC-1 system",
  cave: "Cave",
  chihiro: "Sega Chihiro",
  cps1: "CPS1",
  cps2: "CPS2",
  cps3: "CPS3",
  cv1k: "Cave CV1000",
  djmain: "Konami Beatmania",
  eolith: "Eolith",
  firebeat: "Konami FireBeat",
  ksys573: "Konami S573",
  lindbergh: "Sega Lindbergh",
  megatech: "Megatech",
  metro: "Metro",
  midtunit: "Midway TUS",
  mitchell: "Mitchell",
  model1: "Sega Model 1",
  model2: "Sega Model 2",
  model3: "Sega Model 3",
  namcops2: "Namco System 246",
  namcos10: "Namco System 10",
  namcos11: "Namco System 11",
  namcos12: "Namco System 12",
  namcos21: "Namco System 21",
  namcos21_c67: "Namco System 21 C67",
  namcos21_de: "Namco System 21 DE",
  namcos22: "Namco System 22",
  namcos23: "Namco System 23",
  neogeo: "SNK NeoGeo",
  neopcb: "Neo PCB",
  nmk16: "NMK 16",
  pgm2: "IGS PGM2",
  pgm3: "IGS PGM3",
  pgm: "IGS PGM",
  playch10: "Nintendo Playchoice 10",
  segac2: "Sega System C2",
  segas16b: "Sega System 16",
  segas18: "Sega System 18",
  segas24: "Sega System 24",
  segas32: "Sega System 32",
  seta: "Seta1",
  stv: "Sega TV",
  system1: "Sega System 1",
  taito_f2: "Taito F2",
  taito_f3: "Taito F3",
  toaplan2: "Toaplan",
  triforce: "Triforce",
  twinkle: "Twinkle",
  vamphalf: "Hyperstone",
  vsnes: "Nintendo VS UniSystem and DualSystem",
  zn: "Sony ZN",
};
