export enum ContextMenuId {
  CATEGORY = "CATEGORY",
  GAME_NAME = "GAME_NAME",
  GAME_ITEM = "GAME_ITEM",
  ROM_NAME = "ROM_NAME",
  THUMBNAIL = "THUMBNAIL",
  THUMBNAIL_DROPZONE = "THUMBNAIL_DROPZONE",
  SEARCH_RESULT = "SEARCH_RESULT",
  SETTING = "SETTING"
}
