export enum AppEvent {
  CRITICAL_ERROR = "CRITICAL_ERROR",
  MAIN_VIEW_MOUNT = "MAIN_VIEW_MOUNT",
  CONFIG = "CONFIG",
  PLAYLISTS = "PLAYLISTS",
  IS_FILE_EXISTS = "IS_FILE_EXISTS",
  SET_THUMBNAIL = "SET_THUMBNAIL",
  REMOVE_THUMBNAIL = "REMOVE_THUMBNAIL",
  ITEM_UPDATE = "ITEM_UPDATE",
  REFRESH_PLAYLIST = "REFRESH_PLAYLIST",
  REFRESH_PLAYLISTS = "REFRESH_PLAYLISTS"
}
