// TODO : make this mapping to dynamic 
const TeknoParrotProfile = {
    "Too Spicy" : "2Spicy.xml",
    "3D Cosplay Mahjong" : "3DCosplayMahjong.xml",
    "After Burner Climax" : "abc.xml",
    "Akai Katana Shin for NESiCAxLive" : "AkaiKatanaShinNesica.xml",
    "Aquapazza: Aquaplus Dream Match" : "AquapazzaAquaplusDreamMatch.xml",
    "Ge-Sen Love: Plus Pengo!" : "ArcadeLove.xml",
    "Arcana Heart 2 for NESiCAxLive" : "ArcanaHeart2Nesica.xml",
    "Arcana Heart 3 (eX-Board)" : "ArcanaHeart3Exboard.xml",
    "Arcana Heart 3: LOVE MAX SixStarS!!!!!!" : "ArcanaHeart3Nesica.xml",
    "Batman" : "Batman.xml",
    "Battle Fantasia" : "BattleFantasia.xml",
    "Battle Fantasia Network Edition for NESiCAxLive" : "BattleFantasiaNesica.xml",
    "Battle Gear 4" : "BattleGear4.xml",
    "Battle Gear 4 Tuned" : "BattleGear4Tuned.xml",
    "BlazBlue: Central Fiction" : "BBCF.xml",
    "BlazBlue: Chronophantasma" : "BBCP.xml",
    "Blade Arcus" : "BladeArcus.xml",
    "Blade Strangers" : "BladeStrangers.xml",
    "BlazBlue: Calamity Trigger" : "BlazBlueCalaminityTrigger.xml",
    "BlazBlue: Continuum Shift" : "BlazBlueContinuumShift.xml",
    "BlazBlue: Continuum Shift II" : "BlazBlueContinuumShift2.xml",
    "Border Break Scramble" : "BorderBreakScramble.xml",
    "Caladrius AC" : "CaladriusAC.xml",
    "Chaos Code" : "CC.xml",
    "Chaos Breaker" : "ChaosBreaker.xml",
    "Chaos Code: New Sign of Catastrophe v1.03.00" : "ChaosCodeNSOC103.xml",
    "Chaos Code: New Sign of Catastrophe v2.11" : "ChaosCodeNSOC211.xml",
    "Chase H.Q. 2" : "ChaseHQ2.xml",
    "Crimzon Clover for NESiCAxLive" : "CrimzonClover.xml",
    "Counter-Strike Neo" : "CSNEO.xml",
    "Daemon Bride: Additionnal Gain" : "DaemonBrideAG.xml",
    "Daemon Bride (eX-Board)" : "DaemonBrideExboard.xml",
    "Dariusburst: Another Chronicle" : "DariusBurst.xml",
    "Daytona Championship USA" : "Daytona3.xml",
    "Dirty Drivin'" : "DirtyDrivin.xml",
    "Dead or Alive 5 Ultimate Arcade" : "DOA5.xml",
    "Do Not Fall: Run For Your Drink" : "DoNotFallRunforYourDrink.xml",
    "Dragon Dance for NESiCAxLive" : "DragonDanceNesica.xml",
    "Elevator Action for NESiCAxLive" : "ElevatorAction.xml",
    "En-Eins Perfektewelt for NESiCAxLive" : "EnEinsPerfektewelt.xml",
    "Exception for NESiCAxLive" : "ExceptionNesica.xml",
    "Dengeki Bunko: Fighting Climax" : "FightingClimax.xml",
    "Fighting Climax Ignition" : "FightingClimaxIgnition.xml",
    "The Fast and the Furious" : "FNF.xml",
    "The Fast and the Furious Drift" : "FNFDrift.xml",
    "The Fast and the Furious Super Bikes" : "FNFSB.xml",
    "Super Bikes 2" : "FNFSB2.xml",
    "The Fast and the Furious SuperCars" : "FNFSC.xml",
    "Ford Racing: Full Blown" : "FR.xml",
    "Gaelco Championship Tuning Race" : "GaelcoChampionshipTuningRace.xml",
    "Gaia Attack 4" : "GaiaAttack4.xml",
    "SEGA Golden Gun" : "GG.xml",
    "Guilty Gear Xrd REV2" : "GGXrd.xml",
    "Guilty Gear Xrd -SIGN-" : "GGXrdSIGN.xml",
    "Guilty Gear XX Accent Core Plus R" : "GGXX.xml",
    "Guitar Hero Arcade" : "GHA.xml",
    "GigaWing Generations" : "GigaWingGenerations.xml",
    "Gouketsuji Ichizoku: Senzo Kuyou for NESiCAxLive" : "Goketsuji.xml",
    "GRID" : "GRID.xml",
    "Groove Coaster 2: Heavenly Festival" : "GrooveCoaster2.xml",
    "Ghost Squad Evolution" : "GSEVO.xml",
    "GTI Club: Supermini Festa!" : "GtiClub3.xml",
    "H2Overdrive" : "H2Overdrive.xml",
    "Homura for NESiCAxLive" : "Homura.xml",
    "The House of the Dead 4" : "HOTD4.xml",
    "Hyper Street Fighter II - The Anniversary Edition for NESiCAxLive" : "HyperStreetFighterII.xml",
    "Initial D: Arcade Stage 4 (Export)" : "ID4Exp.xml",
    "Initial D: Arcade Stage 4 (Japanese)" : "ID4Jap.xml",
    "Initial D: Arcade Stage 5 (Export)" : "ID5.xml",
    "Initial D: Arcade Stage 6 Double Ace" : "ID6.xml",
    "Initial D: Arcade Stage 7 Double Ace Cross" : "ID7.xml",
    "Initial D: Arcade Stage 8 Infinity" : "ID8.xml",
    "Initial D: Arcade Stage Zero" : "IDZ.xml",
    "Ikaruga for NESiCAxLive" : "Ikaruga.xml",
    "Justice League - Heroes United" : "JusticeLeague.xml",
    "The King of Fighters '98 Ultimate Match Final Edition for NESiCAxLive" : "KingofFighters98UltimateMatchFinalEditionNesica.xml",
    "The King of Fighters '98 Ultimate Match" : "KingofFighters98UnlimitedMatch.xml",
    "KOF Maximum Impact Regulation A" : "KingofFightersMaximumImpactRegulationA.xml",
    "KOF Sky Stage" : "KingofFightersSkyStage.xml",
    "The King of Fighters XII" : "KingofFightersXII.xml",
    "The King of Fighters XIII" : "KingofFightersXIII.xml",
    "King of Fighters XIII Climax" : "KingofFightersXIIIClimax.xml",
    "King of Fighters XIII Climax (Nesica)" : "KingofFightersXIIIClimaxNesica.xml",
    "K.O. Drive (Prototype)" : "KODrive.xml",
    "Koihime Enbu" : "Koihime.xml",
    "Let's Go Island: Lost on the Island of Tropics" : "LGI.xml",
    "Let's Go Island 3D: Lost on the Island of Tropics" : "LGI3D.xml",
    "Let's Go Jungle: Lost on the Island of Spice" : "LGJ.xml",
    "Let's Go Jungle Special" : "LGJS.xml",
    "Let's Go Safari" : "LGS.xml",
    "Lost Land Adventure" : "LostLand.xml",
    "Luigi's Mansion Arcade" : "LuigisMansion.xml",
    "Lupin 3" : "Lupin3.xml",
    "Magical Beat" : "MagicalBeat.xml",
    "maimai GreeN" : "MaiMaiGreen.xml",
    "Melty Blood: Actress Again - Current Code" : "MB.xml",
    "Super Monkey Ball: Ticket Blitz" : "Mballblitz.xml",
    "Melty Blood (RE2)" : "MeltyBloodRE2.xml",
    "Mario Kart: Arcade GP DX" : "MKDX.xml",
    "Mario Kart DX USA" : "MKDXUSA.xml",
    "MachStorm" : "MS.xml",
    "Nitro+ Blasterz: Heroines Infinite Duel" : "NitroplusBlasterz.xml",
    "Operation G.H.O.S.T." : "OG.xml",
    "OutRun 2 SP SDX" : "or2spdlx.xml",
    "P4U: Persona 4 The Ultimate in Mayonaka Arena" : "Persona4A.xml",
    "P4UU: Persona 4 The Ultimax Ultra Suplex Hold" : "Persona4U.xml",
    "Phantom Breaker: Another Code" : "PhantomBreaker.xml",
    "Pokkén Tournament" : "PokkenTournament.xml",
    "Gouketsuji Ichizoku: Senzo Kuyou (Taito Type X2)" : "PowerInstinctV.xml",
    "Puyo Puyo!! Quest Arcade" : "PPQ.xml",
    "Project Diva Arcade" : "ProjectDiva.xml",
    "Puzzle Bobble for NESiCAxLive" : "PuzzleBobble.xml",
    "R-Tuned : Ultimate Street Racing" : "R-Tuned.xml",
    "Raiden III" : "RaidenIII.xml",
    "Raiden III for NESiCAxLive" : "RaidenIIINesica.xml",
    "Raiden IV" : "RaidenIV.xml",
    "Raiden IV for NESiCAxLive" : "RaidenIVNesica.xml",
    "Rambo" : "Rambo.xml",
    "Rastan Saga for NESiCAxLive" : "RastanSaga.xml",
    "Ring Riders" : "RingRiders.xml",
    "Rumble Fish 2 for NESiCAxLive, The" : "RumbleFish2Nesica.xml",
    "Samurai Spirits Sen" : "SamuraiSpiritsSen.xml",
    "School of Ragnarok" : "SchoolOfRagnarok.xml",
    "Dream Raiders" : "SDR.xml",
    "SEGA Race TV" : "segartv.xml",
    "Senko no Ronde: DUO - Dis-United Order" : "SenkoNoRondeDuo.xml",
    "Senko no Ronde: DUO - Dis-United Order for NESiCAxLive" : "SenkoNoRondeDuoNesica.xml",
    "Shikigami no Shiro III" : "Shigami3.xml",
    "Shining Force: Cross Elysion" : "ShiningForceCrossElysion.xml",
    "Shining Force: Cross Exlesia" : "ShiningForceCrossExlesia.xml",
    "Shining Force: Cross Raid" : "ShiningForceCrossRaid.xml",
    "Skullgirls 2nd Encore" : "Skullgirls2E.xml",
    "Winter X Games SnoCross" : "SnoCross.xml",
    "Space Invaders for NESiCAxLive" : "SpaceInvaders.xml",
    "Spica Adventure" : "SpicaAdventure.xml",
    "SEGA Rally 3" : "SR3.xml",
    "SEGA Racing Classic" : "SRC.xml",
    "Sonic &#38; SEGA All-Stars Racing" : "SSASR.xml",
    "Star Trek Voyager" : "StarTrekVoyager.xml",
    "STAR WARS: Battle Pod" : "StarWars.xml",
    "Strania -The Stella Machina-" : "StraniaTheStellaMachina.xml",
    "Street Fighter III: 3rd Strike - Fight for the Future for NESiCAxLive" : "StreetFighterIII3rdStrike.xml",
    "Street Fighter IV" : "StreetFighterIV.xml",
    "Street Fighter V: Type Arcade" : "StreetFighterVTypeArcade.xml",
    "Street Fighter Zero 3 for NESiCAxLive" : "StreetFighterZero3.xml",
    "Suggoi! Arcana Heart 2 for NESiCAxLive" : "SuggoiArcanaHeart2Nesica.xml",
    "Super Street Fighter IV: Arcade Edition" : "SuperStreetFighterIVArcadeEdition.xml",
    "Super Street Fighter IV: Arcade Edition (Export)" : "SuperStreetFighterIVArcadeEditionEXP.xml",
    "Super Street Fighter IV: Arcade Edition Ver. 2012" : "SuperStreetFighterIVArcadeEditionVer2012.xml",
    "Taisen Hot Gimmick 5: Mirai Eigou" : "TaisenHotGimmick5.xml",
    "Taisen Mix Party" : "TaisenMixParty.xml",
    "Tekken 7" : "Tekken7.xml",
    "Tekken 7: Fated Retribution" : "Tekken7FR.xml",
    "Tekken 7: Fated Retribution - Round 2" : "Tekken7R2.xml",
    "Tetris: The Grand Master 3 - Terror-Instinct" : "TetrisTheGrandMaster3TerrorInstinct.xml",
    "Theatrhythm Final Fantasy: All-Star Carnival" : "Theatrhythm.xml",
    "Tokyo Cop" : "TokyoCop.xml",
    "Transformers: Human Alliance" : "Transformers.xml",
    "Trouble Witches AC" : "TroubleWitches.xml",
    "Trouble Witches AC for NESiCAxLive" : "TroubleWitchesNesica.xml",
    "Under Defeat HD+" : "UDX.xml",
    "Ultra Street Fighter IV" : "UltraStreetFighterIV.xml",
    "Under Night In-Birth" : "UnderNightInBirth.xml",
    "Under Night In-Birth Exe:Late[st]" : "UnderNightInBirthExeLatest.xml",
    "Vampire Savior: The Lord of Vampire for NESiCAxLive" : "VampireSavior.xml",
    "Virtua Fighter 5 (Version B)" : "VF5B.xml",
    "Virtua Fighter 5 (Version C)" : "VF5C.xml",
    "Valve Limit R" : "VirtuaRLimit.xml",
    "Virtua Tennis 3" : "VT3.xml",
    "Virtua Tennis 4" : "VT4.xml",
    "Wacky Races" : "WackyRaces.xml",
    "Wangan Midnight Maximum Tune 5" : "WMMT5.xml",
    "Wangan Midnight Maximum Tune 6" : "WMMT6.xml",
    "Yugioh 5DS Duel Terminal 6 (USA)" : "YugiohDT6U.xml",
}

export const getTeknoParrotProfile = (gameName:string) : string => {
    if (TeknoParrotProfile.hasOwnProperty(gameName)) {
        return TeknoParrotProfile[gameName];
    }
    return "";
}