export enum AppEvent {
  OPEN_DEV_TOOLS = "OPEN_DEV_TOOLS",
  RELOAD = "RELOAD",
  WRITE_JIMP_IMAGE = "WRITE_JIMP_IMAGE",
  WRITE_JIMP_IMAGE_SUCCESS = "WRITE_JIMP_IMAGE_SUCCESS",
  WRITE_JIMP_IMAGE_ERROR = "WRITE_JIMP_IMAGE_ERROR",
  SET_APP_CONFIG = "SET_APP_CONFIG",
  SET_EXPLORER_CONFIG = "SET_EXPLORER_CONFIG",
  SET_ITEM_FILTER = "SET_ITEM_FILTER",
  SAVE_SETTING = "SAVE_SETTING"
}
