export enum ContextMenuId {
    PLAYLIST = "PLAYLIST",
    GAME_ITEM = "GAME_ITEM",
    GAME_NAME = "GAME_NAME",
    ROM_PATH = "ROM_PATH",
    THUMBNAIL = "THUMBNAIL",
    DROPZONE_BOXART = "DROPZONE_BOXART",
    DROPZONE_TITLESCREEN = "DROPZONE_TITLESCREEN",
    DROPZONE_SNAPSHOT = "DROPZONE_SNAPSHOT",
}